services:
  resullme:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    env_file:
      - ./.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=https://models.inference.ai.azure.com
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_TIMEOUT=300
      - OPENAI_MAX_RETRIES=3
